version: "3.7"

services:
  postgres:
    image: postgres
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - continuoustest-db:/var/lib/postgresql/data

  continuoustest:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - postgres
    ports:
      - "4000:4000"

volumes:
  continuoustest-db:
